version: '2'

services:
  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload #remove in production
        "application.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true' # displays stdout
    volumes:
      - '.:/application' # take . and mount in app folder
    ports:
      - '8000:8000' #host:remote